import Head from "next/head";
import { createWallet } from "../lib/utility";

export default function Identity() {
  const testWallet = async () => {
    const result = await createWallet("testwallet");
    console.log(result);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='motion-safe:animate-fadeIn min-h-[calc(100vh-325px)]'>
        <section className='flex flex-col px-3 py-8 lg:h-[300px]  md:px-5  lg:max-w-7xl lg:mx-auto '>
          <div className='text-center'>
            <h1 className='text-6xl font-FredokaOne mt-16 tracking-tight'>
              IDENTITY API
            </h1>
            <p className='text-zinc-400 text-sm mt-4 tracking-wide'>
              Allow users to create a wallet easily and quickly with
              utlity.ai&apos;s identity API...
            </p>
            <div className='mx-auto w-24 h-1 my-12 bg-gradient-to-r from-zinc-500 to-zinc-400 rounded-full'></div>
          </div>
        </section>
        <section className='lg:max-w-[900px] mx-auto'>
          <div
            onClick={() => testWallet()}
            className='hover:scale-105 font-extrabold transition-all cursor-pointer mt-8 w-[300px] text-center mx-auto bg-gradient-to-r from-blue-500 to-blue-700 py-3 px-5 text-2xl text-zinc-900 font-FredokaOne tracking-wider'
          >
            {" "}
            CREATE WALLET
          </div>
        </section>
      </main>
    </div>
  );
}
