import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://utiliti.ai'>utiliti.ai </a>Firebase
          boilerplate
        </h1>

        <p className={styles.description}>
          Get started by forking this repo
          <code className={styles.code}>
            https://github.com/elonsdev/utiliti-boilerplate
          </code>
        </p>

        <div className={styles.grid}>
          <a href='https://utiliti.ai/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about utiliti.ai features and API.</p>
          </a>

          <a href='https://utiliti.ai/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about utiliti.ai!</p>
          </a>
        </div>
      </main>
    </div>
  );
}
